# Makefile for building IETF Internet-Draft
# Local builds: mmark only (brew install mmark)
# CI builds: mmark + xml2rfc for official IETF-compliant outputs

DRAFTS := $(wildcard draft-*.md)
XML_FILES := $(DRAFTS:.md=.xml)
HTML_FILES := $(DRAFTS:.md=.html)
TXT_FILES := $(DRAFTS:.md=.txt)

.PHONY: all clean xml html check-tools

# Default target: build XML and HTML using mmark only
all: check-tools xml html

check-tools:
	@which mmark > /dev/null || (echo "ERROR: mmark not found. Install with: brew install mmark" && exit 1)
	@echo "✓ mmark is installed"

xml: $(XML_FILES)

html: $(HTML_FILES)

txt: $(TXT_FILES)

%.xml: %.md
	@echo "Building $@ from $<"
	mmark $< > $@

%.html: %.md
	@echo "Building $@ from $<"
	mmark -html $< > $@


clean:
	rm -f $(XML_FILES) $(HTML_FILES) $(TXT_FILES)
	@echo "Cleaned generated files"

.PHONY: help
help:
	@echo "IETF Draft Build System"
	@echo ""
	@echo "Available targets:"
	@echo "  all        - Build XML and HTML using mmark (default)"
	@echo "  xml        - Build only XML files"
	@echo "  html       - Build only HTML files for preview"
	@echo "  clean      - Remove all generated files"
	@echo "  check-tools - Verify mmark is installed"
	@echo "  help       - Show this help message"
	@echo ""
	@echo "Requirements:"
	@echo "  mmark      - brew install mmark"
	@echo ""
	@echo "Note: HTML generated by mmark is for preview only."
	@echo "      Authors won't display in local HTML."
	@echo "      GitHub Actions generates official HTML with xml2rfc."
